"""add total_cost_usd to pipeline_runs

Revision ID: b042d394006d
Revises: f87e03439726
Create Date: 2026-04-02 16:35:37.040924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b042d394006d'
down_revision: Union[str, Sequence[str], None] = 'f87e03439726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('total_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'total_cost_usd')
    # ### end Alembic commands ###
