"""create phase1 tables

Revision ID: f87e03439726
Revises:
Create Date: 2026-04-02 08:05:59.268023

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f87e03439726'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheets_row_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_content_items_sheets_row_id'),
        'content_items',
        ['sheets_row_id'],
        unique=True,
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('rows_added', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('result_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_pipeline_runs_workflow_id'),
        'pipeline_runs',
        ['workflow_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_runs_workflow_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_content_items_sheets_row_id'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
